name: Java CI with Allure
on:
  schedule:
    - cron: "0 21 * * *"
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
  checks: write
jobs:
  run-java-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # DEBUG STEPS
      - name: Debug - Check secrets
        run: |
          echo "=== ENVIRONMENT VARIABLES DEBUG ==="
          echo "API_USER_EMAIL is set: $([[ -n "$API_USER_EMAIL" ]] && echo "YES" || echo "NO")"
          echo "API_USER_PASSWORD is set: $([[ -n "$API_USER_PASSWORD" ]] && echo "YES" || echo "NO")"  
          echo "BASE_URL is set: $([[ -n "$BASE_URL" ]] && echo "YES" || echo "NO")"
          echo "BASE_URL value: $BASE_URL"
          echo "API_USER_EMAIL length: ${#API_USER_EMAIL}"
          echo "API_USER_PASSWORD length: ${#API_USER_PASSWORD}"
          echo "=== END DEBUG ==="
        env:
          API_USER_EMAIL: ${{ secrets.API_USER_EMAIL }}
          API_USER_PASSWORD: ${{ secrets.API_USER_PASSWORD }}
          BASE_URL: ${{ secrets.BASE_URL }}

      - name: Debug - Test connection to API
        run: |
          echo "Testing connection to BASE_URL..."
          curl -I "$BASE_URL" || echo "Connection failed"
        env:
          BASE_URL: ${{ secrets.BASE_URL }}

      - name: Debug - Run single test class
        run: |
          echo "Running only the failing test class..."
          ./gradlew test --tests "*TransactionManagement*" --info --stacktrace
        env:
          API_USER_EMAIL: ${{ secrets.API_USER_EMAIL }}
          API_USER_PASSWORD: ${{ secrets.API_USER_PASSWORD }}
          BASE_URL: ${{ secrets.BASE_URL }}

      - name: Run tests with Allure
        run: ./gradlew clean test allureReport --info --stacktrace
        env:
          API_USER_EMAIL: ${{ secrets.API_USER_EMAIL }}
          API_USER_PASSWORD: ${{ secrets.API_USER_PASSWORD }}
          BASE_URL: ${{ secrets.BASE_URL }}

      - name: Upload Allure results as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: build/allure-results

      - name: Deploy Allure Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/reports/allure-report
          publish_branch: gh-pages