name: Java CI with Allure

on:
  schedule:
    - cron: "0 21 * * *"
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write
  checks: write

jobs:
  run-java-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-${{ runner.os }}-

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Run tests
        run: ./gradlew clean test
        env:
          EMAIL: ${{ secrets.API_USER_EMAIL }}
          PASSWORD: ${{ secrets.API_USER_PASSWORD }}
          BASE_URL: ${{ secrets.BASE_URL }}

      - name: Install Allure Commandline
        if: always()
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
          wget https://github.com/allure-framework/allure2/releases/download/2.21.0/allure-2.21.0.zip
          unzip -o allure-2.21.0.zip -d /opt/
          sudo ln -s /opt/allure-2.21.0/bin/allure /usr/bin/allure

      - name: Generate Allure Report Static HTML
        if: always()
        run: |
          allure generate build/allure-results -o build/allure-report --clean

      - name: Deploy Allure Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: build/allure-report
